name: "Send message in Telegram"
description: "Send message whith bot in telegram"

inputs:
  BOTTOKEN:
      description: "{{secrets.SURGETOKEN}}"
      required: true
      
outputs:
  message:
    description: "Response message"

runs:
  using: "node12"
  main: "dist/index.js"