name: example_workflow
on:
 push:
  branches:
   - react_app_deploy
 
jobs:
  Build job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Run
        run: |
         npm install
         npm run build
      - name: Up
        uses: actions/upload-artifact@v2

  Deploy job:
    runs-on: ubuntu-latest
    needs: Build job
    steps:
      - name: Download
        uses: actions/download-artifact@v2
      - name: To deploy
        uses: dswistowski/surge-sh-action@v1





