name: send_telegram_workflow

on:
  push:
    branches:
      - send_telegram_action

jobs:
  envio_mensaje:
    name: envio_mensaje
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Message
        uses: ./.github/actions/SendMessageTelegram
      - name: Push changes to repository
        run: |
          git config user.name viceentcb
          git config user.email viceentcb@gmail.com
          git add .
          git commit -m "Proof commit"
          git push origin send_telegram_action
