name: send_telegram_workflow

on:
  push:
    branches:
      - send_telegram_action

jobs:
  envio_mensaje:
    name: envio_mensaje
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send Message
        uses: ./.github/actions/SendMessageTelegram
        with:
          TokenBot: ${{secrets.BOTTOKEN }}
          ChatId: ${{secrets.CHAT_ID }}
          Name: "Canario"



